---
- name: Ensure firewall is installed
  ansible.builtin.apt:
    package: ufw
    state: present
  become: true

- name: Ensure firewall service is running
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: true
  become: true

- name: Enable firewall
  community.general.ufw:
    state: enabled
  become: true

- name: Configure default policies
  community.general.ufw:
    default: "{{ item.policy }}"
    direction: "{{ item.direction }}"
  loop:
    - { policy: deny, direction: incoming }
    - { policy: allow, direction: outgoing }
  become: true

- name: Allow SSH connections
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
  become: true
  notify: Reload firewall

- name: Register firewall's status
  ansible.builtin.command:
    cmd: ufw status verbose
  changed_when: false
  register: firewall_status_verbose
  become: true

- name: Print firewall's status
  ansible.builtin.debug:
    var: firewall_status_verbose.stdout_lines
