---
- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
  become: true

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
  become: true
