---
- name: Set environment variables
  ansible.builtin.lineinfile:
    path: "/home/{{ username }}/.bashrc"
    line: "{{ item }}"
    state: present
  loop:
    - export EDITOR='vim'
    - export PAGER='less'
    - export LESS='-igRFXM --tabs=4 --mouse'
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - LC_CTYPE=en_US.UTF-8

- name: Enable vi mode in Bash
  ansible.builtin.lineinfile:
    path: "/home/{{ username }}/.bashrc"
    line: "set -o vi"
    state: present

- name: Configure Vim
  ansible.builtin.copy:
    src: vimrc
    dest: "/home/{{ username }}/.vimrc"
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ username }}"
  become: true

- name: Configure readline
  ansible.builtin.copy:
    src: inputrc
    dest: "/home/{{ username }}/.inputrc"
    mode: "0644"
    owner: "{{ username }}"
    group: "{{ username }}"
  become: true
