---
- name: VPS Server Set-Up
  hosts: remotehost
  gather_facts: true

  vars_prompt:
    - name: username
      prompt: The name of a user to create
      private: false
    - name: password
      prompt: The password of a user to create
      private: true
      encrypt: sha512_crypt
      confirm: true
      salt_size: 8
    - name: ssh_config_server_alias
      prompt: The server's alias to be used in the local SSH config
      private: false
    - name: timezone
      prompt: The server's timezone
      default: "Europe/Moscow"
      private: false
    - name: apt_upgrade
      prompt: Upgrade packages (yes/no)?
      default: "yes"
      private: false
    - name: container_runtime
      prompt: "Choose container runtime (k3s/docker/none)"
      default: "none"
      private: false
  vars:
    ssh_key_filename: "id_rsa_{{ ssh_config_server_alias }}@{{ username }}"
    ssh_port: "2000"

  pre_tasks:
    - name: Ensure OS is Debian-based
      ansible.builtin.assert:
        that:
          - ansible_facts.os_family in ['Debian']
        fail_msg: "This playbook only supports Debian-based systems"

    - name: Ensure SSH port is valid
      ansible.builtin.assert:
        that:
          - ssh_port | int <= 65535
        fail_msg: "SSH port must be less than or equal to 65535"

    - name: Register localhost user
      ansible.builtin.command:
        cmd: whoami
      changed_when: false
      delegate_to: localhost
      register: local_whoami

    - name: Register architecture
      ansible.builtin.command:
        cmd: dpkg --print-architecture
      changed_when: false
      register: arch
      become: true

    - name: Register distribution codename
      ansible.builtin.shell:
        cmd: source /etc/os-release && echo "${VERSION_CODENAME}"
        executable: /bin/bash
      changed_when: false
      register: distrib_codename
      become: true

    - name: Set remotehost IP
      ansible.builtin.set_fact:
        remote_ipv4: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"

    - name: Set SSH target host
      ansible.builtin.set_fact:
        ssh_target_host: "{{ ansible_host | default(remote_ipv4) }}"

  roles:
    - role: system
      tags: [system, packages]

    - role: logging
      tags: [logging]

    - role: user
      tags: [user]

    - role: security
      tags: [security]

    - role: k3s
      when: container_runtime == "k3s"
      tags: [k3s]

    - role: docker
      when: container_runtime == "docker"
      tags: [docker]

  post_tasks:
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Reboot the server
      ansible.builtin.command: systemctl reboot
      async: 1
      poll: 0
      changed_when: true
      become: true

    - name: Use the new user and SSH port
      ansible.builtin.set_fact:
        ansible_user: "{{ username }}"
        ansible_port: "{{ ssh_port }}"
        ansible_ssh_private_key_file: "~/.ssh/{{ ssh_key_filename }}"
        ansible_ssh_common_args: "-o IdentitiesOnly=yes"

    - name: Reconnect
      ansible.builtin.meta: reset_connection

    - name: Wait for SSH to accept connections
      ansible.builtin.wait_for_connection:
        timeout: 300
